import type { CityAnalysis } from "@/lib/types";

// Analisi del territorio — comune 072021 (Gioia del Colle).
// Contenuto trascritto dal report markdown + design Claude Design (.dc).
// id_analysis derivato dall'header del report ("Generata il 26/06/2026, 11:19:35").

export const ANALISI_072021: CityAnalysis = {
  istat: "072021",
  idAnalysis: "072021-20260626-111935",
  comune: "Gioia del Colle",
  provincia: "Città Metropolitana di Bari",
  generatedAt: "2026-06-26T11:19:35Z",
  disclaimer:
    "Analisi automatica basata sui soli dati pubblici citati. Non costituisce materiale elettorale né parere legale o urbanistico; i dati ISTAT (Censimento 2011) sono una fotografia strutturale e i vincoli idrogeologici ISPRA vanno verificati puntualmente sul PAI vigente.",
  intro: {
    eyebrow: "Quadro di sintesi",
    title: "Tre leve strutturali, un portafoglio da sbloccare",
    text: "Gioia del Colle (~26.615 abitanti) è un comune di collina interna con una base imprenditoriale diffusa, un profilo demografico in rapido invecchiamento e un nodo ferroviario raro per l'entroterra pugliese. Sui fondi di coesione registra 753 progetti per 260,5 M€ di costo pubblico, ma con uno spend ratio globale del 46,6% frenato dai grandi cantieri stradali.",
  },
  kpis: [
    { value: "26.615", label: "Abitanti", sub: "OpenCoesione 2026",
      info: "Popolazione residente di Gioia del Colle secondo i dati OpenCoesione aggiornati al 28/02/2026. È il denominatore di riferimento per gli indicatori pro-capite citati nell'analisi." },
    { value: "753", label: "Progetti di coesione", sub: "617 conclusi (81,9%)",
      info: "Numero totale di progetti finanziati dalle politiche di coesione (fondi UE e nazionali) localizzati sul territorio comunale. 617 risultano conclusi (81,9%), segnale di una buona capacità realizzativa storica dell'ente. Fonte: OpenCoesione, dati al 28/02/2026." },
    { value: "260,5 M€", label: "Costo pubblico", sub: "121,4 M€ pagati",
      info: "Costo pubblico totale dei 753 progetti di coesione. Di questi, 121,4 M€ risultano effettivamente pagati (erogati ai beneficiari). La differenza è la quota impegnata ma non ancora spesa. Fonte: OpenCoesione." },
    { value: "46,6%", label: "Spend ratio globale", sub: "trasporti fermi al 27,1%",
      info: "Rapporto tra pagamenti effettuati (121,4 M€) e costo pubblico totale (260,5 M€): misura quanto delle risorse impegnate è stato davvero speso. Il tema Trasporti, fermo al 27,1%, trascina giù la media complessiva. Fonte: OpenCoesione." },
    { value: "157,1", label: "Indice di vecchiaia", sub: "Italia 2011 ~148",
      info: "Numero di residenti over-65 ogni 100 under-15. Valori sopra 100 indicano una popolazione che invecchia; 157,1 supera la media nazionale del 2011 (~148) e segnala una pressione crescente sui servizi socio-assistenziali. Dato strutturale ISTAT, Censimento 2011." },
    { value: "852 m", label: "Stazione dal centro", sub: "linea Bari–Taranto",
      info: "Distanza della stazione ferroviaria (linea Bari–Taranto) dal centro abitato. Una dotazione di mobilità su ferro rara per un comune dell'entroterra murgiano, e una leva per l'intermodalità ferro-gomma. Fonte: OpenStreetMap." },
  ],
  highlights: [
    {
      value: "27,1%",
      label: "Spend ratio trasporti e mobilità",
      text: "Oltre 106 M€ programmati non spesi. Il cantiere SS 100 (84 M€) è di fatto fermo allo 0,53%.",
      color: "#A8432A",
      info: "Spend ratio del tema Trasporti e mobilità: 39,5 M€ pagati su 145,7 M€ finanziati. È il valore più basso del portafoglio comunale: oltre 106 M€ restano da spendere, con rischio di disimpegno automatico delle risorse UE (regola N+3). Fonte: OpenCoesione.",
    },
    {
      value: "78,1%",
      label: "Spend ratio inclusione sociale",
      text: "La performance migliore del portafoglio: 10,6 M€ pagati su 13,5 M€, 49 progetti conclusi.",
      color: "#2C5545",
      info: "Spend ratio del tema Inclusione sociale: 10,6 M€ pagati su 13,5 M€ finanziati, 49 progetti. È la performance migliore del portafoglio e dimostra una capacità di spesa consolidata dell'Ambito territoriale BA13 in ambito welfare. Fonte: OpenCoesione.",
    },
  ],
  swot: [
    {
      label: "Forze",
      tag: "Punti di forza",
      color: "#2C5545",
      items: [
        { title: "Nodo ferroviario strategico", text: "Stazione a 852 m dal centro sulla Bari–Taranto, 40 fermate bus e 2 autostazioni: una dotazione di mobilità rara per l'entroterra pugliese." },
        { title: "Patrimonio storico-culturale", text: "2 musei (Museo Archeologico Nazionale), 14 monumenti, Parco di Monte Sannace e Castello normanno-svevo." },
        { title: "Base imprenditoriale solida", text: "2.056 unità locali attive e 6.048 addetti; 569 unità nel commercio (27,7% del totale)." },
        { title: "Buona capacità gestionale", text: "617 progetti conclusi su 753 (81,9%) e spend ratio inclusione sociale al 78,1%." },
      ],
    },
    {
      label: "Debolezze",
      tag: "Criticità",
      color: "#B5752B",
      items: [
        { title: "Trasporti quasi fermi", text: "Spend ratio 27,1%: oltre 106 M€ programmati non spesi, trainati dal cantiere SS 100 (0,53%)." },
        { title: "Disoccupazione giovanile 36,5%", text: "NEET 15-29 al 23,4% e tasso di occupazione complessivo al 39,6% (Censimento 2011)." },
        { title: "Territorio che invecchia", text: "Indice di vecchiaia 157,1, grandi anziani 75+ al 10,8%, dipendenza strutturale al 52,1%." },
        { title: "Capitale umano poco qualificato", text: "Solo il 23,0% dei 30-34enni è laureato; il 35,8% ha la sola licenza media." },
      ],
    },
    {
      label: "Opportunità",
      tag: "Da cogliere",
      color: "#3A5A8C",
      items: [
        { title: "Candidatura 'Città d'arte'", text: "Monte Sannace + Museo Nazionale + Castello: il riconoscimento R.R. 11/2004 aprirebbe linee di finanziamento dedicate." },
        { title: "Nodo ferro-gomma", text: "Stazione e 40 fermate per intercettare i pendolari verso Bari e Taranto; aggancio al progetto 'Wi-Life Station'." },
        { title: "Welfare finanziabile", text: "Spend ratio inclusione 78,1%: ben posizionati su PN Metro Plus, FSE+ e PNRR Missione 5." },
        { title: "Mobilità FESR", text: "Il rinnovo flotta TPL provinciale (14,3 M€) è un comparabile diretto per il PR Puglia FESR." },
      ],
    },
    {
      label: "Minacce",
      tag: "Rischi",
      color: "#A8432A",
      items: [
        { title: "Rischio idraulico", text: "Il 5,9% del territorio (P2+P3) con 1.075 residenti esposti: verifiche PAI e maggiori costi di progetto." },
        { title: "Pressione socio-assistenziale", text: "Vecchiaia 157,1 e grandi anziani 75+ al 10,8% caricano i servizi comunali." },
        { title: "Disimpegno fondi UE", text: "I cantieri SS 100 (0,53%) e km 7+200 (48%) a rischio regola N+3: oltre 100 M€ da perdere." },
        { title: "Fuga dei giovani", text: "Disoccupazione 36,5% e bassa laurea (23,0%) alimentano l'emigrazione qualificata." },
      ],
    },
  ],
  proposte: [
    { id: "prop-ss100", type: "proposta", category: "Mobilità", badges: ["Capacità di spesa 27%", "Senza nuovo finanziamento"],
      title: "Sblocco del cantiere SS 100 — Tavolo di crisi interistituzionale",
      text: "Tavolo permanente tra Comune, Città Metropolitana di Bari, ANAS e Autorità di Gestione del PR Puglia FESR per il monitoraggio mensile del cantiere SS 100 (84 M€, spend ratio 0,53%) e della messa in sicurezza km 7+200–44+500 (32,1 M€, 48%). Azione di advocacy e raccordo per prevenire il disimpegno automatico (regola N+3) e accelerare i 106 M€ ancora non spesi.",
      funding: "Nessun finanziamento aggiuntivo — coordinamento istituzionale" },
    { id: "prop-hub", type: "proposta", category: "Mobilità", badges: ["Fattibilità media", "Capacità di spesa 27%"],
      title: "Hub di interscambio ferro-gomma alla stazione",
      text: "Nodo intermodale presso la stazione (852 m dal centro): parcheggio di attestamento, bike-sharing, pensiline bus con informazioni in tempo reale e percorso pedonale protetto verso il centro storico. In partenariato con RFI e SUD EST, agganciato al progetto 'Wi-Life Station' (7,5 M€).",
      funding: "PR Puglia FESR 2021-2027, Asse 3 — Mobilità sostenibile" },
    { id: "prop-cultura", type: "proposta", category: "Cultura", badges: ["Fattibilità media"],
      title: "Itinerario 'Città dei Normanni e dei Messapi'",
      text: "Sistema unico tra Castello normanno-svevo, Museo Archeologico Nazionale, Parco di Monte Sannace ed Ex Sito Jupiter: segnaletica unificata, biglietteria integrata e materiali multilingue. Accompagnato dalla candidatura formale a 'Città d'arte' (R.R. 11/2004).",
      funding: "PR Puglia FESR Asse 5 · FSC — Patto per la Puglia" },
    { id: "prop-welfare", type: "proposta", category: "Welfare", badges: ["Fattibilità alta", "Capacità di spesa 78%"],
      title: "Welfare di prossimità per anziani: ADI e centri diurni",
      text: "Ampliamento dell'assistenza domiciliare integrata e dei centri diurni per non autosufficienti, in risposta all'indice di vecchiaia 157,1 e ai grandi anziani 75+ (10,8%). Comune capofila del Distretto BA13 con ASL BA e Terzo Settore.",
      funding: "PNRR Missione 5 C2 · FSE+ 2021-2027 — Priorità 4" },
    { id: "prop-neet", type: "proposta", category: "Lavoro", badges: ["Fattibilità media"],
      title: "'Gioia Lavora' — orientamento e inserimento dei NEET",
      text: "Programma di orientamento, formazione duale e tirocini retribuiti per i giovani NEET 15-29 (23,4%), sui settori a domanda locale: commercio, agricoltura e terziario. Con il Centro per l'Impiego, ANPAL Servizi e le associazioni di categoria.",
      funding: "Programma GOL — PNRR M5C1 · FSE+ 2021-2027 — Priorità 1" },
    { id: "prop-duc", type: "proposta", category: "Commercio", badges: ["Governance · basso costo di avvio"],
      title: "Distretto Urbano del Commercio (DUC) del centro storico",
      text: "Istituzione di un DUC (L.R. Puglia 11/2003): marketing territoriale condiviso, segnaletica commerciale integrata con quella culturale e incentivi al reinsediamento nei locali sfitti. Sulla base di 569 unità locali nel commercio (27,7%).",
      funding: "L.R. Puglia 11/2003 · PR Puglia FESR Asse 5" },
  ],
  idee: [
    { id: "idea-duc", type: "idea", category: "Commercio", badges: [],
      title: "DUC: valorizzare una base imprenditoriale con governance condivisa",
      text: "569 unità locali nel commercio (~20 esercizi/1.000 ab.): una base matura per un DUC che coordini promozione, orari e digitalizzazione e acceda ai bandi regionali. Avvio in 6-12 mesi, fase iniziale 200-500 mila €." },
    { id: "idea-welfare", type: "idea", category: "Welfare", badges: ["Fattibilità alta · spesa 78%"],
      title: "Rete di prossimità per anziani fragili",
      text: "Assistenza domiciliare leggera (telesoccorso, spesa, accompagnamento), volontariato e coordinamento digitale tra Comune, ASL BA e Terzo Settore. Innesto sul track record di inclusione sociale (13,5 M€, spend ratio 0,78)." },
    { id: "idea-sanita", type: "idea", category: "Sanità", badges: ["Fattibilità alta"],
      title: "Farmacia dei Servizi come hub di telemedicina",
      text: "Modello 'Farmacia dei Servizi' su 3-4 delle 8 farmacie: ECG, saturimetria, prenotazione CUP e consegna a domicilio per anziani. Quadro normativo già operativo (D.Lgs. 153/2009), fondi PNRR Missione 6." },
    { id: "idea-istruzione", type: "idea", category: "Istruzione", badges: ["Fattibilità alta"],
      title: "Contrasto alla dispersione e capitale umano adulto",
      text: "Tutoraggio e sportelli psico-pedagogici nei plessi (17, 3.387 alunni) contro l'uscita precoce (13,3%); CPIA e corsi serali per gli adulti con sola licenza media (35,8%). Su PN Scuola e Competenze 2021-2027." },
    { id: "idea-tpl", type: "idea", category: "Mobilità", badges: ["Finanziabile ora · spesa 27%"],
      title: "Rinnovo flotta TPL e integrazione ferro-gomma",
      text: "Navette elettriche che collegano i comuni del Distretto BA13 alla stazione, con orari sincronizzati ai treni RFI e bigliettazione integrata. Comparabile provinciale: rinnovo flotta TPL (14,25 M€). Lotto iniziale 2-4 M€." },
    { id: "idea-circolare", type: "idea", category: "Ambiente", badges: ["Fatto altrove · spesa 63%"],
      title: "Hub di economia circolare per il ciclo dei rifiuti",
      text: "Consorzio intercomunale BA13 per un centro di raccolta e valorizzazione, compostaggio di comunità e repair café per ~50.000 abitanti. Modello comparabile in provincia (14,99 M€). Spend ratio Ambiente 63,1%." },
    { id: "idea-tecnonidi", type: "idea", category: "Impresa", badges: ["Fatto altrove"],
      title: "Incubatore agri-tech e food-tech (Fondo TecnoNidi)",
      text: "Spazio di co-working e incubazione per startup agroalimentari e di agricoltura di precisione, in connessione con le filiere locali (olio, vino, caseari). Con Puglia Sviluppo. Lotto iniziale 1-3 M€." },
    { id: "idea-intermodale", type: "idea", category: "Mobilità", badges: [],
      title: "Hub intermodale leggero alla stazione",
      text: "Deposito bici sicuro, info-point bus, colonnine di ricarica e totem di info-mobilità che integra orari treno e bus, per risolvere il 'primo e ultimo miglio'. Accordo con RFI in 12-18 mesi; 300-800 mila €." },
    { id: "idea-idraulica", type: "idea", category: "Ambiente", badges: ["Fattibilità media"],
      title: "Invarianza idraulica e laminazione diffusa",
      text: "Piano Comunale di Invarianza Idraulica integrato al PUG: vasche di prima pioggia, aree verdi permeabili e 'strade spugna' nelle aree P2/P3 (671 residenti esposti), trasformando il rischio in spazi pubblici fruibili." },
    { id: "idea-sannace", type: "idea", category: "Cultura", badges: ["Fattibilità media"],
      title: "Monte Sannace come polo di turismo lento",
      text: "Itinerario 'Gioia Archeologia e Memoria' tra Parco di Monte Sannace, Museo Nazionale ed Ex Sito Jupiter: turismo lento a piedi e in bici, QR narrativi multilingue e info-point condiviso. 300-800 mila €." },
  ],
  marketing: [
    { group: "Turismo & cultura", items: [
      { id: "mk-itinerario", type: "marketing", category: "Cultura", badges: ["Fattibilità media"],
        title: "Itinerario Castello–Monte Sannace con storytelling digitale",
        text: "Brand narrativo unitario tra Castello normanno-svevo e Parco di Monte Sannace, con segnaletica direzionale (DM 557/1999) e racconto digitale (QR, audioguida open-source). Precedente: 'Cammino dei Castelli Normanni' di Melfi (PZ)." },
      { id: "mk-jupiter", type: "marketing", category: "Cultura", badges: ["Fattibilità bassa"],
        title: "Ex Sito Jupiter: turismo della memoria della Guerra Fredda",
        text: "L'ex base missilistica NATO (1961-63), unica in Puglia, come nicchia di Cold War tourism per il segmento internazionale. Precedente: 'Museo della Guerra Fredda' di Niscemi (CL). Richiede accordo con il Ministero della Difesa." },
    ]},
    { group: "Attrattività & brand", items: [
      { id: "mk-brand", type: "marketing", category: "Impresa", badges: ["Fattibilità media"],
        title: "Brand agroalimentare 'Gioia del Colle DOP/DOC' — enoturismo",
        text: "Unico comune con DOP casearia (Mozzarella, 2023) e DOC vitivinicola (Primitivo): pacchetto enoturistico unitario con mappa delle cantine e 'weekend del gusto'. Precedente: Castelvetro di Modena (Lambrusco + caseario)." },
    ]},
    { group: "Viabilità & mobilità", items: [
      { id: "mk-bici", type: "marketing", category: "Mobilità", badges: ["Fattibilità media"],
        title: "Nodo intermodale stazione–bici: porta turistica",
        text: "Noleggio bici e info-mobilità turistica nel nodo ferroviario (852 m dal centro), agganciato al cantiere 'Wi-Life Station' (7,5 M€, 48%). Precedente: 'Bici in Stazione' di Manfredonia (FG)." },
    ]},
    { group: "Sicurezza & vivibilità", items: [
      { id: "mk-ccn", type: "marketing", category: "Commercio", badges: ["Fattibilità media"],
        title: "Centro Commerciale Naturale: animazione serale del centro storico",
        text: "Coordinamento tra esercenti, Comune e Pro Loco per serate a tema, mercatini e illuminazione condivisa: animazione degli spazi pubblici e sicurezza percepita. Precedente: 'Centro Commerciale Naturale Conversano' (BA)." },
    ]},
  ],
  fonti: [
    { src: "JSON", name: "OpenCoesione — aggregati Gioia del Colle", meta: "livello comunale" },
    { src: "JSON", name: "ISPRA IdroGEO — rischio idrogeologico (072021)", meta: "livello comunale" },
    { src: "CSV", name: "ISTAT ASIA — unità locali e addetti (2023)", meta: "livello comunale" },
    { src: "CSV", name: "ISTAT 8milaCensus — indicatori (Censimento 2011)", meta: "livello comunale" },
    { src: "CSV", name: "MIUR Open Data — anagrafe scuole (a.s. 2026/27)", meta: "livello comunale" },
    { src: "CSV", name: "Ministero della Salute — anagrafe farmacie", meta: "livello comunale" },
    { src: "OSM", name: "OpenStreetMap — relation 40721", meta: "livello comunale" },
    { src: "JSON", name: "OpenCoesione — Fondo TecnoNidi (7PUA0308.10)", meta: "comparabile provinciale" },
    { src: "JSON", name: "OpenCoesione — Tecnologie ciclo rifiuti (1AGCOE1756)", meta: "comparabile provinciale" },
    { src: "JSON", name: "OpenCoesione — Rinnovo flotta TPL (1AGCOE170)", meta: "comparabile provinciale" },
    { src: "JSON", name: "OpenCoesione — Scheda 37 cliniche (1PUFE3.100242)", meta: "comparabile provinciale" },
    { src: "JSON", name: "OpenCoesione — CNRBIOMICS (1MISEPIR01_00017)", meta: "livello comunale" },
  ],
};
